### ISSUE TITLE
Trying to build this on Freebsd getting errors

### ISSUE THREAD

**Issue by camrun91** [Corvusoft/restbed#113]
I am trying to build this on freebsd (freenas jail) and I get this error /root/dev/restbed/source/corvusoft/restbed/uri.cpp:30:12: error: 'std::stoi' has not been declared
 using std::stoi;
            ^ 
I am using your code so the c library files are included. Any help would be great.

**Comment by ben-crowhurst** [comment]
Looking into this now, bare with us.

**Comment by camrun91** [comment]
Ok just so you know I got that error when compiling with gcc49 and g++49 I get [  5%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/uri.cpp.o
/root/dev/restbed/source/corvusoft/restbed/uri.cpp:6:10: fatal error: 'regex' file not found
#include <regex>
         ^
When I I try to make using clang.

**Comment by ben-crowhurst** [comment]
Ok attempting to build on FreeBSD 10.2 - Clang 3.4.1

**Comment by ben-crowhurst** [comment]
You're using HEAD, yes?

**Comment by camrun91** [comment]
OK looks like I am still on freebsd 9.3 and clang is 3.4.1
 What do you mean using HEAD ?

**Comment by ben-crowhurst** [comment]
[What is GIT HEAD?](http://stackoverflow.com/questions/2304087/what-is-head-in-git)

Ok I have a clean build on FreeBSD with Clang, please check and confirm your Jail configuration.

**Comment by camrun91** [comment]
Yes I am using HEAD and am on FreeBSD 9.3 and clang 3.4.1

**Comment by ben-crowhurst** [comment]
@camrun91 Have you validated the available paths within your Jail setup?

**Comment by camrun91** [comment]
What paths do I need to validate against?

**Comment by ben-crowhurst** [comment]
Search for the missing headers, regex and string.

```
find / -name "regex" -print 
```

**Comment by camrun91** [comment]
Ok I switched back to gcc49 as the find above found the regex in gcc49. But now I am getting the original error again.

**Comment by camrun91** [comment]
OK so it looks like I may have got it to go a little further now. I ran cmake with gcc49 and g++49 and forced c11 libs. But know I am getting these errors. 

dev/restbed/build # make -j 5 install
Scanning dependencies of target restbed
[ 29%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/uri.cpp.o
[ 29%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/rule.cpp.o
[ 29%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/http.cpp.o
[ 29%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/string.cpp.o
[ 29%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/request.cpp.o
[ 35%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/service.cpp.o
/root/dev/restbed/source/corvusoft/restbed/string.cpp: In static member function 'static std::basic_string<char>::size_type restbed::String::format(std::string&, std::basic_string<char>::size_type, const char*, __va_list_tag*)':
/root/dev/restbed/source/corvusoft/restbed/string.cpp:165:90: error: 'vsnprintf' was not declared in this scope
         int required_length = vsnprintf( formatted.get( ), length + 1, format, arguments );
                                                                                          ^
/root/dev/restbed/source/corvusoft/restbed/uri.cpp:30:12: error: 'std::stoi' has not been declared
 using std::stoi;
            ^
/root/dev/restbed/source/corvusoft/restbed/uri.cpp:36:12: error: 'std::snprintf' has not been declared
 using std::snprintf;
            ^
/root/dev/restbed/source/corvusoft/restbed/uri.cpp:37:12: error: 'std::to_string' has not been declared
 using std::to_string;
            ^
/root/dev/restbed/source/corvusoft/restbed/uri.cpp: In member function 'uint16_t restbed::Uri::get_port() const':
/root/dev/restbed/source/corvusoft/restbed/uri.cpp:213:28: error: '::to_string' has not been declared
                     port = ::to_string( ntohs( entry->s_port ) );
                            ^
/root/dev/restbed/source/corvusoft/restbed/uri.cpp:223:52: error: 'stoi' was not declared in this scope
         return static_cast< uint16_t >( stoi( port ) );
                                                    ^
*** [CMakeFiles/restbed.dir/source/corvusoft/restbed/string.cpp.o] Error code 1
/root/dev/restbed/source/corvusoft/restbed/uri.cpp:224:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
*** [CMakeFiles/restbed.dir/source/corvusoft/restbed/uri.cpp.o] Error code 1
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_header(const string&, int&, int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:162:46: error: 'stoi' was not declared in this scope
             value = stoi( get_header( name ) );
                                              ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_header(const string&, long int&, long int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:174:46: error: 'stol' was not declared in this scope
             value = stol( get_header( name ) );
                                              ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_header(const string&, float&, float) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:186:46: error: 'stof' was not declared in this scope
             value = stof( get_header( name ) );
                                              ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_header(const string&, double&, double) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:198:46: error: 'stod' was not declared in this scope
             value = stod( get_header( name ) );
                                              ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_header(const string&, long long int&, long long int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:210:47: error: 'stoll' was not declared in this scope
             value = stoll( get_header( name ) );
                                               ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_header(const string&, unsigned int&, unsigned int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:222:47: error: 'stoul' was not declared in this scope
             value = stoul( get_header( name ) );
                                               ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_header(const string&, long unsigned int&, long unsigned int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:234:47: error: 'stoul' was not declared in this scope
             value = stoul( get_header( name ) );
                                               ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_header(const string&, long long unsigned int&, long long unsigned int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:246:48: error: 'stoull' was not declared in this scope
             value = stoull( get_header( name ) );
                                                ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_query_parameter(const string&, int&, int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:296:55: error: 'stoi' was not declared in this scope
             value = stoi( get_query_parameter( name ) );
                                                       ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_query_parameter(const string&, long int&, long int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:308:55: error: 'stol' was not declared in this scope
             value = stol( get_query_parameter( name ) );
                                                       ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_query_parameter(const string&, float&, float) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:320:55: error: 'stof' was not declared in this scope
             value = stof( get_query_parameter( name ) );
                                                       ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_query_parameter(const string&, double&, double) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:332:55: error: 'stod' was not declared in this scope
             value = stod( get_query_parameter( name ) );
                                                       ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_query_parameter(const string&, long long int&, long long int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:344:56: error: 'stoll' was not declared in this scope
             value = stoll( get_query_parameter( name ) );
                                                        ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_query_parameter(const string&, unsigned int&, unsigned int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:356:56: error: 'stoul' was not declared in this scope
             value = stoul( get_query_parameter( name ) );
                                                        ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_query_parameter(const string&, long unsigned int&, long unsigned int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:368:56: error: 'stoul' was not declared in this scope
             value = stoul( get_query_parameter( name ) );
                                                        ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_query_parameter(const string&, long long unsigned int&, long long unsigned int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:380:57: error: 'stoull' was not declared in this scope
             value = stoull( get_query_parameter( name ) );
                                                         ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_path_parameter(const string&, int&, int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:447:54: error: 'stoi' was not declared in this scope
             value = stoi( get_path_parameter( name ) );
                                                      ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_path_parameter(const string&, long int&, long int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:459:54: error: 'stol' was not declared in this scope
             value = stol( get_path_parameter( name ) );
                                                      ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_path_parameter(const string&, float&, float) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:471:54: error: 'stof' was not declared in this scope
             value = stof( get_path_parameter( name ) );
                                                      ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_path_parameter(const string&, double&, double) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:483:54: error: 'stod' was not declared in this scope
             value = stod( get_path_parameter( name ) );
                                                      ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_path_parameter(const string&, long long int&, long long int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:495:55: error: 'stoll' was not declared in this scope
             value = stoll( get_path_parameter( name ) );
                                                       ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_path_parameter(const string&, unsigned int&, unsigned int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:507:55: error: 'stoul' was not declared in this scope
             value = stoul( get_path_parameter( name ) );
                                                       ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_path_parameter(const string&, long unsigned int&, long unsigned int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:519:55: error: 'stoul' was not declared in this scope
             value = stoul( get_path_parameter( name ) );
                                                       ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp: In member function 'void restbed::Request::get_path_parameter(const string&, long long unsigned int&, long long unsigned int) const':
/root/dev/restbed/source/corvusoft/restbed/request.cpp:531:56: error: 'stoull' was not declared in this scope
             value = stoull( get_path_parameter( name ) );
                                                        ^
*** [CMakeFiles/restbed.dir/source/corvusoft/restbed/request.cpp.o] Error code 1
/root/dev/restbed/source/corvusoft/restbed/service.cpp:44:12: error: 'std::to_string' has not been declared
 using std::to_string;
            ^
*** [CMakeFiles/restbed.dir/source/corvusoft/restbed/service.cpp.o] Error code 1
4 errors
*** [CMakeFiles/restbed.dir/all] Error code 2
1 error
*** [all] Error code 2
1 error
root@Home_assistant:~/dev/restbed/build #

**Comment by ben-crowhurst** [comment]
OK, I've managed to replicate your issue by downgrading my OS and using G++4.9.  Let me see what I can do.

**Comment by ben-crowhurst** [comment]
The cause of the GCC issues are outlined on the FreeBSD mailing list, [g++ cannot find std::stoi](https://lists.freebsd.org/pipermail/freebsd-ports/2014-June/092782.html). 

Given that FreeBSD has dropped shipping GCC with future releases, I'm reluctant to spend any more time on this issue.

I'd recommend install Clang++ correctly and working from that toolchain.

**Comment by camrun91** [comment]
Ok so I build with clang and clang++ and get this.
 cmake -DCMAKE_C_COMPILER=clang -DCMAKE _CXX_COMPILER=clang++ -std=c++11 -lc++abi [-D BUILD_TESTS=YES] [-D BUILD_EXAMPLES=YES] [-D BUILD_SSL=NO] [-D BUILD_SHARED=YES] [-D CMAKE_INSTALL_PREFIX=/output-directory] ..
-- The C compiler identification is Clang 3.4.1
-- The CXX compiler identification is Clang 3.4.1
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
   Copyright 2013-2016, Corvusoft Ltd, All Rights Reserved.
-- Found ASIO include at: /root/dev/restbed/dependency/asio/asio/include
-- Found OpenSSL library at: /usr/lib/libssl.so
-- Found OpenSSL include at: /usr/include
-- Found Crypto library at: /usr/lib/libcrypto.so
-- Configuring done
-- Generating done
-- Build files have been written to: /root/dev/restbed/build

root@Home_assistant:~/dev/restbed/build # make -j 5 install                                 Scanning dependencies of target restbed
[  5%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/uri.cpp.o
[ 11%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/http.cpp.o
[ 17%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/rule.cpp.o
[ 23%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/string.cpp.o
[ 29%] Building CXX object CMakeFiles/restbed.dir/source/corvusoft/restbed/request.cpp.o
/root/dev/restbed/source/corvusoft/restbed/http.cpp:6:10: fatal error: 'memory' file not found
In file included from /root/dev/restbed/source/corvusoft/restbed/rule.cpp:8:
/root/dev/restbed/source/corvusoft/restbed/rule.hpp:9:10: fatal error: 'memory' file not found
#include <memory>
         ^
#include <memory>
         ^
/root/dev/restbed/source/corvusoft/restbed/string.cpp:6:10: fatal error: 'cstdio' file not found
/root/dev/restbed/source/corvusoft/restbed/uri.cpp:6:10: fatal error: 'regex' file not found
#include <cstdio>
         ^
/root/dev/restbed/source/corvusoft/restbed/request.cpp:6:10: fatal error: 'utility' file not found
#include <regex>
         ^
#include <utility>
         ^
1 error generated.
1 error generated.
*** [CMakeFiles/restbed.dir/source/corvusoft/restbed/rule.cpp.o] Error code 1
*** [CMakeFiles/restbed.dir/source/corvusoft/restbed/string.cpp.o] Error code 1
1 error generated.
*** [CMakeFiles/restbed.dir/source/corvusoft/restbed/uri.cpp.o] Error code 1
1 error generated.
*** [CMakeFiles/restbed.dir/source/corvusoft/restbed/http.cpp.o] Error code 1
1 error generated.
*** [CMakeFiles/restbed.dir/source/corvusoft/restbed/request.cpp.o] Error code 1
5 errors
*** [CMakeFiles/restbed.dir/all] Error code 2
1 error
*** [all] Error code 2
1 error

I can not for the life of me figure out what in the world is going on here any help would be awesome.

**Comment by ben-crowhurst** [comment]
I'd really like to help, but without access to your local environment there is very little I can do.  This appears to be a local configuration issue as core files are absent.  Try running ` sudo find / -name "memory" -print` It may be a permission issue/restriction due to your jail configuration... or get out of jail all together?

**Comment by ben-crowhurst** [comment]
How are we getting on?

**Comment by camrun91** [comment]
I have set up a clean jail but have not had a chance to test this out yet. I hopefully will have time to test this later this evening.

**Comment by ben-crowhurst** [comment]
Any room for an update regarding your troubles?

**Comment by camrun91** [comment]
I actually went a different route. Thanks for your help.

**Comment by ben-crowhurst** [comment]
Not a problem.  Best of luck.
